[workspace]
members = [
    "02_hello_cargo",
    "03_guessing_game",
    "04_variables",
    "05_data_type",
    "06_functions",
    "07_branches",
    "08_loops",
    "09_ownership",
    "10_structs", 
    "11_rectangles"
]

# 设置包解析器版本
resolver = "2"